sudo: required
services:
  - docker

before_install:
  - docker build -t rjpdeen/docker-react -f Dockerfile.dev .

script:
  - docker run rjpdeen/docker-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-916503846740"
  bucket_path: "docker-react"
  
  on:
    branch: master
  access_key_id: "$AWS-ACCESS-KEY"
  secret_access_key:
    secure: "$AWS-SECRET-KEY"
